config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders
  resources :products
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :product
    belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @orders = Order.includes(:product).all
        @summary = Order.group(:product_id).count
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params.merge(status: 'Inactive'))

        if @product.save
            redirect_to products_path
        else
            render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
    
        if @product.update(product_params)
            redirect_to products_path
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
    
        redirect_to root_path
    end

    private

    def product_params
        params.require(:product).permit(:product_name, :product_description, :quantity, :price, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flowerstoreph</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders List</h1>
<table>
    <tr>
        <th> Order ID </th>
        <th> Product Name </th>
        <th> Price </th>
    </tr>
    <% @orders.each do |order| %>
        <tr>
            <td> <%= order.id %> </td>
            <td> <%= order.product.product_name %> </td>
            <td> <%= order.price %> </td>
        </tr>
    <% end %>
</table>

<h1>Orders Summary</h1>
<table>
    <tr>
        <th> Product Name </th>
        <th> Orders </th>
        <th> Total Price </th>
    </tr>
    <% @summary.each do |i| %>
        <tr>
            <td> <%= Product.find(i[0]).product_name %> </td>
            <td> <%= i[1] %> </td>
            <td> <%= Order.where(product_id: i[0]).sum(:price) %></td>
        </tr>
    <% end %>
</table>

app/views/products/edit.html.erb
<h1>New Product</h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
  </div>

  <div>
    <%= form.label :product_description %><br>
    <%= form.text_field :product_description %>
  </div>

  <div>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price, step: :any %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ["Inactive", "Active"] %>
  </div>

 <br>

  <div>
    <%= form.submit 'Update' %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |product| %>
    <p>
        Product Name: <%= link_to product.product_name, product %> <br>
        Product Description: <%= product.product_description %> <br>
        Price: <%= product.price %> <br>
        <%= link_to "Edit", edit_product_path(product) %>
        <%= link_to "Destroy", product_path(product),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </p>
<% end %>

<p>
    <%= link_to "Add New Product", new_product_path %>
</p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
  </div>

  <div>
    <%= form.label :product_description %><br>
    <%= form.text_field :product_description %>
  </div>

  <div>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price, step: :any %>
  </div>
    <br>
  <div>
    <%= form.submit 'Add' %>
  </div>
<% end %>

app/views/products/show.html.erb
<h2><%= @product.product_name %></h2>
<p>
    <%= @product.product_description %> <br>
    Price: <%= @product.price %> <br>
    Qty: <%= @product.quantity %> <br>
</p>